# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detail.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetailWidget(object):
    def setupUi(self, DetailWidget):
        DetailWidget.setObjectName("DetailWidget")
        DetailWidget.resize(539, 331)
        self.label = QtWidgets.QLabel(DetailWidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DetailWidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.TenHSLabel = QtWidgets.QLabel(DetailWidget)
        self.TenHSLabel.setGeometry(QtCore.QRect(80, 100, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TenHSLabel.setFont(font)
        self.TenHSLabel.setObjectName("TenHSLabel")
        self.SoGiaoDucLabel = QtWidgets.QLabel(DetailWidget)
        self.SoGiaoDucLabel.setGeometry(QtCore.QRect(10, 60, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SoGiaoDucLabel.setFont(font)
        self.SoGiaoDucLabel.setObjectName("SoGiaoDucLabel")
        self.tableWidget = QtWidgets.QTableWidget(DetailWidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 140, 541, 192))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)

        self.retranslateUi(DetailWidget)
        QtCore.QMetaObject.connectSlotsByName(DetailWidget)

    def retranslateUi(self, DetailWidget):
        _translate = QtCore.QCoreApplication.translate
        DetailWidget.setWindowTitle(_translate("DetailWidget", "Học bạ chi tiết"))
        self.label.setText(_translate("DetailWidget", "HỌC BẠ ĐIỆN TỬ"))
        self.label_2.setText(_translate("DetailWidget", "Tên HS: "))
        self.TenHSLabel.setText(_translate("DetailWidget", "unknown"))
        self.SoGiaoDucLabel.setText(_translate("DetailWidget", "unknown"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DetailWidget", "Môn học"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DetailWidget", "Lớp"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DetailWidget", "Điểm"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DetailWidget", "Xếp Loại"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("DetailWidget", "Giáo viên"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DetailWidget = QtWidgets.QWidget()
    ui = Ui_DetailWidget()
    ui.setupUi(DetailWidget)
    DetailWidget.show()
    sys.exit(app.exec_())
