# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soResult.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SoResultWidget(object):
    def setupUi(self, SoResultWidget):
        SoResultWidget.setObjectName("SoResultWidget")
        SoResultWidget.resize(404, 357)
        self.label = QtWidgets.QLabel(SoResultWidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 481, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.SogiaoducLabel = QtWidgets.QLabel(SoResultWidget)
        self.SogiaoducLabel.setGeometry(QtCore.QRect(20, 80, 441, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SogiaoducLabel.setFont(font)
        self.SogiaoducLabel.setObjectName("SogiaoducLabel")
        self.tableWidget = QtWidgets.QTableWidget(SoResultWidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 120, 491, 241))
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        self.retranslateUi(SoResultWidget)
        QtCore.QMetaObject.connectSlotsByName(SoResultWidget)

    def retranslateUi(self, SoResultWidget):
        _translate = QtCore.QCoreApplication.translate
        SoResultWidget.setWindowTitle(_translate("SoResultWidget", "Tìm theo sở giáo dục"))
        self.label.setText(_translate("SoResultWidget", "HỌC BẠ ĐIỆN TỬ"))
        self.SogiaoducLabel.setText(_translate("SoResultWidget", "Sở giáo dục và đào tạo"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SoResultWidget", "Mã học bạ"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SoResultWidget", "Tên học sinh"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("SoResultWidget", "Địa chỉ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("SoResultWidget", "Thao tác"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SoResultWidget = QtWidgets.QWidget()
    ui = Ui_SoResultWidget()
    ui.setupUi(SoResultWidget)
    SoResultWidget.show()
    sys.exit(app.exec_())
