# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tenResult.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tenResultWidget(object):
    def setupUi(self, tenResultWidget):
        tenResultWidget.setObjectName("tenResultWidget")
        tenResultWidget.resize(529, 329)
        self.label = QtWidgets.QLabel(tenResultWidget)
        self.label.setGeometry(QtCore.QRect(0, 20, 531, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Label = QtWidgets.QLabel(tenResultWidget)
        self.Label.setGeometry(QtCore.QRect(20, 70, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Label.setFont(font)
        self.Label.setObjectName("Label")
        self.tableWidget = QtWidgets.QTableWidget(tenResultWidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 110, 531, 221))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.TenhocsinhLabel = QtWidgets.QLabel(tenResultWidget)
        self.TenhocsinhLabel.setGeometry(QtCore.QRect(190, 70, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TenhocsinhLabel.setFont(font)
        self.TenhocsinhLabel.setObjectName("TenhocsinhLabel")

        self.retranslateUi(tenResultWidget)
        QtCore.QMetaObject.connectSlotsByName(tenResultWidget)

    def retranslateUi(self, tenResultWidget):
        _translate = QtCore.QCoreApplication.translate
        tenResultWidget.setWindowTitle(_translate("tenResultWidget", "Tìm kiếm theo tên"))
        self.label.setText(_translate("tenResultWidget", "HỌC BẠ ĐIỆN TỬ"))
        self.Label.setText(_translate("tenResultWidget", "Tìm kiếm theo tên: "))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("tenResultWidget", "Mã học bạ"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("tenResultWidget", "Tên học sinh"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("tenResultWidget", "Địa chỉ"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("tenResultWidget", "Sở giáo dục"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("tenResultWidget", "Thao tác"))
        self.TenhocsinhLabel.setText(_translate("tenResultWidget", "1"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tenResultWidget = QtWidgets.QWidget()
    ui = Ui_tenResultWidget()
    ui.setupUi(tenResultWidget)
    tenResultWidget.show()
    sys.exit(app.exec_())
